name = "forge"
compatibility_date = "2024-01-01"
pages_build_output_dir = "apps/forge/dist"

[env.production]
vars = { ENVIRONMENT = "production", VITE_API_BASE_URL = "https://acroniq-forge.onrender.com" }

[env.preview]
vars = { ENVIRONMENT = "preview", VITE_API_BASE_URL = "https://acroniq-forge.onrender.com" }

[build]
command = "pnpm install && pnpm run build:forge"
cwd = "."
