// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/forge-layout/CommandVariant.tsx": () => import("../components/mockups/forge-layout/CommandVariant.tsx"),
  "./components/mockups/forge-layout/ObsidianVariant.tsx": () => import("../components/mockups/forge-layout/ObsidianVariant.tsx"),
  "./components/mockups/forge-layout/TerminalVariant.tsx": () => import("../components/mockups/forge-layout/TerminalVariant.tsx")
};
